baseURL: 'http://www.taiaquapower.com'
title: 台灣智能漁電科技股份有限公司
author: username
languageCode: zh
defaultContentLanguage: zh
defaultContentLanguageInSubdir: false
enableInlineShortcodes: true
theme: tella
enableRobotsTXT: true
Languages:
  zh:
    languageCode: zh-TW
    languageName: 繁體中文
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  showBlog: false
  mainSections:
    - blog
  googleFonts: true
  logo:
    main: img/logo.svg
    alt: TIAQUA Logo
    size: h-14
  site:
    name: 台灣智能漁電科技股份有限公司
  icon:
    fontawesome: true
  homepage_meta_tags:
    meta_description: ''
    meta_og_title: 台灣智能漁電科技股份有限公司
    meta_og_type: website
    meta_og_url: 'http://www.taiaquapower.com'
    meta_og_image: ''
    meta_og_description: ''
    meta_twitter_card: summary_large_image
    meta_twitter_site: '@username'
    meta_twitter_creator: '@username'

menu:
  main:
    - identifier: about
      name: 關於我們
      url: /about/
      weight: 1
    - identifier: service
      name: 服務項目
      url: /service/
      weight: 2
    - identifier: project
      name: 實際案例
      url: /project/
      weight: 3
    - identifier: news
      name: 最新消息
      url: /news/
      weight: 4
    - identifier: contact
      name: 聯絡我們
      url: /contact/
      weight: 5
  footer:
    - name: Home
      url: /
      weight: 1
    #- name: Github
    #  url: 'https://github.com/TIAQUA/TIAQUA-Web'
    #  pre: <i class='icon-github text-2xl'></i>
    #  weight: 2
